baseurl = "https://jorgeikeda.com"
languageCode = "es"
title = "De die in diem"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/freebot\">Jorge Ikeda</a> 2017"
disqusShortname = "shortname"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/freebot"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/jorgeikeda"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

